# Generated by Django 3.2.10 on 2021-12-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
